---
groups:
- name: deploy
  jobs:
  - manually-trigger-deploy
  - bbl-up
  - deploy-cf
- name: delete
  jobs:
  - delete-cf
  - bbl-destroy


resources:
- name: cf-deployment-concourse-tasks
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks
- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment.git
- name: env-repo
  type: git
  source:
    branch: master
    uri: ((env_repo_github_uri))
    private_key: ((hagrid_env_deploy_key))
- name: trigger-deploy
  type: time

jobs:
- name: manually-trigger-deploy
  serial: true
  build_logs_to_retain: 100
  plan:
  - put: trigger-deploy

- name: bbl-up
  serial: true
  build_logs_to_retain: 100
  plan:
  - get: trigger-deploy
    passed: [manually-trigger-deploy]
    trigger: true
  - aggregate:
    - get: env-repo
    - get: cf-deployment-concourse-tasks
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: google_account_creds.json
      BBL_GCP_REGION: us-central1
      LB_DOMAIN: ((system_domain))
      BBL_LB_CERT: ((cf_lb_cert))
      BBL_LB_KEY: ((cf_lb_key))
      BBL_ENV_NAME: rotato
      BBL_STATE_DIR: rotation-cf/bbl-state
    input_mapping:
      bbl-state: env-repo
      bbl-config: env-repo
    ensure:
      put: env-repo
      params:
        repository: updated-bbl-state
        rebase: true

- name: deploy-cf
  build_logs_to_retain: 100
  plan:
  - get: trigger-deploy
    passed: [bbl-up]
    trigger: true
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: cf-deployment
    - get: env-repo
      passed: [bbl-up]
  - task: bosh-upload-stemcell
    file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task.yml
    input_mapping:
      cf-deployment: cf-deployment
      bbl-state: env-repo
    params:
      BBL_STATE_DIR: rotation-cf/bbl-state
      INFRASTRUCTURE: google
  - task: bosh-deploy-cf
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    input_mapping:
      bbl-state: env-repo
      ops-files: cf-deployment
      vars-files: env-repo
    params:
      BBL_STATE_DIR: rotation-cf/bbl-state
      SYSTEM_DOMAIN: ((system_domain))
      OPS_FILES: |
        operations/use-compiled-releases.yml
        operations/scale-database-cluster.yml

- name: delete-cf
  serial: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: env-repo
  - task: delete-deployment-cf
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    input_mapping:
      bbl-state: env-repo
    params:
      BBL_STATE_DIR: rotation-cf/bbl-state

- name: bbl-destroy
  serial: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: env-repo
      passed: [delete-cf]
    - get: cf-deployment-concourse-tasks
  - task: destroy-infrastructure
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    input_mapping:
      bbl-state: env-repo
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: google_account_creds.json
      BBL_STATE_DIR: rotation-cf/bbl-state
    ensure:
      put: env-repo
      params:
        repository: updated-bbl-state
        rebase: true
