---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.11

inputs:
- name: bbl-state  # - The repo containing the Director's bbl state dir
- name: rotato  # - This repo

run:
  path: rotato/tasks/rotate/task

params:
  BBL_STATE_DIR: bbl-state
  # - Path to the directory containing the `bbl-state.json` file
  # - The path is relative to the `bbl-state` input
  # - If blank or '.', uses `bbl-state` input as the location for bbl state
  # - If the specified path does not exist, it will be created

  BOSH_DEPLOYMENT: cf
  # - Required
  # - Name of the BOSH deployment for which CAs need to be rotated

  ROTATE_COMMAND:
  # - Required
  # - Command to be passed to the rotation utility
  # - Supported commands: add-new-cas, regenerate-certs